// Auto-generated by update-sqlite workflow.
// Do not edit manually.

/** SQLite version this build was compiled from. */
export const SQLITE_VERSION = '3.53.0';

/** SQLite git reference used for the build. */
export const SQLITE_REF = 'master';

/** Build variant: bare-bones (reduced binary size, no FTS5/RTREE/JSON/WAL). */
export const BUILD_VARIANT = 'bare-bones';
